

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;


/**
 *
 * @author zarna
 */
public class Juego3 extends javax.swing.JFrame {
    private JButton botones[][];
    private boolean banderaPoner;
    private boolean barrerBoolean;

    /**
     * Creates new form Juego3
     */
    public Juego3() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setResizable(false);
        int[] posMinas = {0,1,2,9};
        
        for(int k=0; k<grafo1.listaady.length; k++){
        for(int l=0; l<posMinas.length; l++){
        if(k==posMinas[l]){
        grafo1.listaady[k].Mine = true;
        }
        }

        }
        
        for(int m=0;m<grafo1.listaady.length;m++){
        if(grafo1.listaady[m].Mine){
            System.out.println(grafo1.listaady[m].Prow+"-"+grafo1.listaady[m].Pcolumn);
        }
        }

        
        
        botones = new JButton[filas1][columnas1];
        for(int i=0; i<filas1; i++){
        for(int j=0; j<columnas1; j++){
        botones[i][j] = new JButton();
        botones[i][j].addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                if (barrerBoolean && !banderaPoner){
                 FActionPerformed(evt);
                }if(!barrerBoolean && banderaPoner){
                 DActionPerformed(evt);
                }
                
            }
        });
        

            
        
  
        botones[i][j].setBackground(Color.white);
        
        botones[i][j].setText(Integer.toString(i)+Integer.toString(j));
        jPanel1.add(botones[i][j]);
        botones[i][j].setName(Integer.toString(i)+Integer.toString(j));
        }
        }
        
    }
    private void DActionPerformed(ActionEvent e) {
            String btn = ((JButton) e.getSource()).getName();
            int f = Integer.parseInt(btn.substring(0,1));
            int c = Integer.parseInt(btn.substring(1,2));
            botones[f][c].setText("B");
            for(int i=0; i<grafo1.listaady.length; i++){
            if(i==grafo1.ind(f,c)){
                
                }
            }

            
        }
        
            }
    
    
    
    
    private void FActionPerformed(java.awt.event.ActionEvent evt){
    
    String btn = ((JButton) evt.getSource()).getName();
    int f = Integer.parseInt(btn.substring(0,1))+1;
    int c = Integer.parseInt(btn.substring(1,2))+1;
    
    grafo1.unir3(grafo1.ind(f,c));
    grafo1.minasAdyacentes();
       // Hay que hacerle una validacion antes
        for(int i=0; i<grafo1.listaady.length; i++){
            if(i==grafo1.ind(f,c)){
                if(grafo1.listaady[i].Mine == true){
                // Muestra todos los numeros de las casillas
                botones[f-1][c-1].setText("*");
                JOptionPane.showMessageDialog(null, "Perdiste");
                this.dispose();
                }else if(grafo1.listaady[i].Mine == false && grafo1.listaady[i].mineAdy>0){
                // Muestra la casilla
                
                int adj = grafo1.listaady[i].mineAdy;
                String adj_str = Integer.toString(adj);
                botones[f-1][c-1].setText(adj_str);
                
                }else if(grafo1.listaady[i].Mine == false && grafo1.listaady[i].mineAdy==0){
                     
                    int adj = grafo1.listaady[i].mineAdy;
                    String adj_str = Integer.toString(adj);
                    botones[f-1][c-1].setText(adj_str);
                    
                    
                    
                //DFS o BFS
                }
            }

            
        }
     
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        barrerBoton = new javax.swing.JToggleButton();
        banderaBoton = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(filas1, columnas1));

        barrerBoton.setText("Barrer on/off");
        barrerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrerBotonActionPerformed(evt);
            }
        });

        banderaBoton.setText("Poner bandera/Quitar bandera");
        banderaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banderaBotonActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cronometro:");

        cronometro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cronometro.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barrerBoton)
                        .addGap(120, 120, 120)
                        .addComponent(banderaBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cronometro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salir)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cronometro))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barrerBoton)
                    .addComponent(banderaBoton)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void banderaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banderaBotonActionPerformed
        if(banderaBoton.isSelected()){
        banderaPoner = true;
        }else{
        banderaPoner = false;
        }
    }//GEN-LAST:event_banderaBotonActionPerformed

    private void barrerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrerBotonActionPerformed
        if(barrerBoton.isSelected()){
        barrerBoolean = true;
        }else{
        barrerBoolean = false;
        }
    }//GEN-LAST:event_barrerBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton banderaBoton;
    private javax.swing.JToggleButton barrerBoton;
    private javax.swing.JLabel cronometro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
